services:
  monitor:
    build: .
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "5300:5300"
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external: true
